name: Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:

    runs-on: ubuntu-20.04

    strategy:
      max-parallel: 3
      matrix:
        php: [ 8.0, 7.4, 7.3 ]
        laravel: [ 8.*, 7.*, 6.*, 5.8.*, 5.7.*, 5.6.* ]
        dependency-version: [ prefer-lowest, prefer-stable ]
        include:
          - laravel: 8.*
            testbench: 6.*
            phpunit: ^8.5
          - laravel: 7.*
            testbench: 5.*
            phpunit: ^8.5
          - laravel: 6.*
            testbench: 4.*
            phpunit: 8.*
          - laravel: 5.8.*
            testbench: 3.8.*
            phpunit: 8.*
          - laravel: 5.7.*
            testbench: 3.7.*
            phpunit: 7.*
          - laravel: 5.6.*
            testbench: 3.6.*
            phpunit: 7.*
        exclude:
          - laravel: 5.7.*
            php: 7.4
          - laravel: 5.6.*
            php: 7.4
          - laravel: 5.7.*
            php: 8.0
          - laravel: 5.6.*
            php: 8.0

    steps:
    - uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php }}
        extensions: xdebug
    - name: Install Dependencies
      run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
    - name: Execute tests (Unit and Feature)
      run: vendor/bin/phpunit --coverage-text
    - name: Static analysis with PHPStan
      run: vendor/bin/phpstan analyse
    - name: Static analysis with Psalm
      run: vendor/bin/psalm
    - name: Coding style PSR12 Check
      run: vendor/bin/phpcs 
